name: CLJS Tests
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: latest

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build JS testing artifacts
        run: npm install && clojure -M:test-cljs
        shell: bash

      - name: Run tests
        run: npx karma start --single-run
