name: Main
on: push
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: latest

      - name: Build jar
        run: clojure -T:build thinjar
        shell: bash

      - name: Push to Clojars
        env:
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        run: clojure -T:build deploy
        shell: bash
