name: Clojure Dependency Checking

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v2

      - name: Check deps
        uses: nnichols/clojure-dependency-update-action@v3
        with:
          github-token: ${{ secrets.github_token }}
